export { Caption } from "./Table/Caption";
export { Col } from "./Table/Col";
export { Colgroup } from "./Table/Colgroup";
export { Pagination } from "./Table/Pagination";
export { Table } from "./Table";
export { Tbody } from "./Table/Tbody";
export { Td } from "./Table/Td";
export { Tfoot } from "./Table/Tfoot";
export { Th } from "./Table/Th";
export { Thead } from "./Table/Thead";
export { Tr } from "./Table/Tr";

export type { ICaption } from "./Table/Caption";
export type { ICol } from "./Table/Col";
export type { IColgroup } from "./Table/Colgroup";
export type { IPagination } from "./Table/Pagination";
export type { ITable } from "./Table";
export type { ITbody } from "./Table/Tbody";
export type { ITd } from "./Table/Td";
export type { ITfoot } from "./Table/Tfoot";
export type { ITh } from "./Table/Th";
export type { IThead } from "./Table/Thead";
export type { ITr } from "./Table/Tr";
